var json = {
	"defaultItem01": {
		"name"		: ["Item Name:" , "Peanut Butter"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"],//Groceries,Pharmacy,Other
		"cost"		: ["Estimated Cost:" , "6"],
		"date"		: ["Date Added:" , ""],	
	},
	"defaultItem02": {
		"name"		: ["Item Name:" , "Cereal"],
		"store"		: ["Store:" , "Albertsons"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "4"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem03": {
		"name"		: ["Item Name:" , "Toilet Paper"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "8"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem04": {
		"name"		: ["Item Name:" , "Laundry Detergent"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "6"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem05": {
		"name"		: ["Item Name:" , "Socks"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Other"], 
		"cost"		: ["Estimated Cost:" , "12"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem06": {
		"name"		: ["Item Name:" , "Potatoes"],
		"store"		: ["Store:" , "Albertsons"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "4"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem07": {
		"name"		: ["Item Name:" , "Carrots"],
		"store"		: ["Store:" , "Albertsons"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "3"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem08": {
		"name"		: ["Item Name:" , "Canned Soup"],
		"store"		: ["Store:" , "Albertsons"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "6"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem09": {
		"name"		: ["Item Name:" , "Lunch Meat"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "8"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem10": {
		"name"		: ["Item Name:" , "Bread"],
		"store"		: ["Store:" , "Fresh and Easy"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "2"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem11": {
		"name"		: ["Item Name:" , "Coffee"],
		"store"		: ["Store:" , "Trader Joes"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "4"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem12": {
		"name"		: ["Item Name:" , "Coffee Filters"],
		"store"		: ["Store:" , "Trader Joes"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "2"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem13": {
		"name"		: ["Item Name:" , "Soda"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "10"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem14": {
		"name"		: ["Item Name:" , "Bottled Water"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "8"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem15": {
		"name"		: ["Item Name:" , "Frozen Burritos"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "11"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem16": {
		"name"		: ["Item Name:" , "Frozen Chicken Breasts"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "12"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem17": {
		"name"		: ["Item Name:" , "Butter"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "6"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem18": {
		"name"		: ["Item Name:" , "Flour"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "14"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem19": {
		"name"		: ["Item Name:" , "Brown Sugar"],
		"store"		: ["Store:" , "Costco"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "4"],
		"date"		: ["Date Added:" , ""],
	},
	"defaultItem20": {
		"name"		: ["Item Name:" , "Milk"],
		"store"		: ["Store:" , "Trader Joes"],
		"budget"	: ["Budget:" , "Groceries"], 
		"cost"		: ["Estimated Cost:" , "3"],
		"date"		: ["Date Added:" , ""],
	},
	
};